import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/ui/header";
import Footer from "../components/ui/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
