import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./providers";
import "./globals.css";
import ModalProvider from "./providers/ModalProvider";
import QueryProvider from "./providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Providers>
            <ModalProvider>{children}</ModalProvider>
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
