export const plans = [
  {
    id: 1,
    name: "Free",
    description:
      "Perfect for individuals getting started with basic project tracking.",
    monthlyAmount: 0,
    yearlyAmount: 0,
    trialDays: 0,
    maxUsers: 1,
    maxProjects: 2,
    support: "Community Support",
    isPopular: false,
    isActive: true,
    features: [
      "Basic task management",
      "Limited projects",
      "Community support",
    ],
  },

  {
    id: 2,
    name: "Starter",
    description: "Ideal for freelancers managing small projects and clients.",
    monthlyAmount: 499,
    yearlyAmount: 4999,
    trialDays: 7,
    maxUsers: 1,
    maxProjects: 5,
    support: "Email Support",
    isPopular: false,
    isActive: true,
    features: [
      "Task & project management",
      "Email notifications",
      "Basic analytics",
    ],
  },

  {
    id: 3,
    name: "Basic",
    description:
      "Best for solo professionals who need more control and reporting.",
    monthlyAmount: 999,
    yearlyAmount: 9999,
    trialDays: 14,
    maxUsers: 1,
    maxProjects: 10,
    support: "Email Support",
    isPopular: false,
    isActive: true,
    features: [
      "Advanced task tracking",
      "Priority email support",
      "Project reports",
    ],
  },

  {
    id: 4,
    name: "Team",
    description: "Designed for small teams collaborating on multiple projects.",
    monthlyAmount: 1999,
    yearlyAmount: 19999,
    trialDays: 14,
    maxUsers: 5,
    maxProjects: 25,
    support: "Priority Email Support",
    isPopular: true,
    isActive: true,
    features: ["Team collaboration", "Role-based access", "Shared dashboards"],
  },

  {
    id: 5,
    name: "Growth",
    description: "For growing teams needing advanced workflows and automation.",
    monthlyAmount: 2999,
    yearlyAmount: 29999,
    trialDays: 14,
    maxUsers: 10,
    maxProjects: 50,
    support: "Chat + Email Support",
    isPopular: false,
    isActive: true,
    features: [
      "Workflow automation",
      "Advanced analytics",
      "Custom task statuses",
    ],
  },

  {
    id: 6,
    name: "Business",
    description:
      "Powerful tools for mid-sized organizations managing complex projects.",
    monthlyAmount: 4999,
    yearlyAmount: 49999,
    trialDays: 30,
    maxUsers: 25,
    maxProjects: 100,
    support: "Priority Chat Support",
    isPopular: false,
    isActive: true,
    features: ["Advanced reporting", "Audit logs", "Team performance insights"],
  },

  {
    id: 7,
    name: "Professional",
    description:
      "Advanced solution for professionals who need full visibility and control.",
    monthlyAmount: 6999,
    yearlyAmount: 69999,
    trialDays: 30,
    maxUsers: 50,
    maxProjects: 200,
    support: "Dedicated Email Support",
    isPopular: false,
    isActive: true,
    features: ["Custom workflows", "API access", "Advanced integrations"],
  },

  {
    id: 8,
    name: "Enterprise",
    description:
      "Enterprise-grade solution with security, scalability, and compliance.",
    monthlyAmount: 9999,
    yearlyAmount: 99999,
    trialDays: 30,
    maxUsers: 100,
    maxProjects: "Unlimited",
    support: "Dedicated Account Manager",
    isPopular: false,
    isActive: true,
    features: [
      "SSO & advanced security",
      "Unlimited projects",
      "Custom integrations",
    ],
  },

  {
    id: 9,
    name: "Enterprise Plus",
    description:
      "Built for large enterprises requiring maximum performance and customization.",
    monthlyAmount: 14999,
    yearlyAmount: 149999,
    trialDays: 30,
    maxUsers: "Unlimited",
    maxProjects: "Unlimited",
    support: "24/7 Dedicated Support",
    isPopular: false,
    isActive: true,
    features: ["24/7 premium support", "Custom SLA", "White-labeling"],
  },

  {
    id: 10,
    name: "Custom",
    description: "Tailored pricing and features based on your business needs.",
    monthlyAmount: 20000,
    yearlyAmount: 400000,
    trialDays: 0,
    maxUsers: "Custom",
    maxProjects: "Custom",
    support: "Dedicated Technical Team",
    isPopular: false,
    isActive: true,
    features: [
      "Custom features",
      "Dedicated infrastructure",
      "Personalized onboarding",
    ],
  },

  {
    id: 11,
    name: "Custom Plus",
    description: "Extended custom plan with premium support.",
    monthlyAmount: 14999,
    yearlyAmount: 149999,
    trialDays: 0,
    maxUsers: "Custom",
    maxProjects: "Custom",
    support: "Dedicated Technical Team",
    isPopular: false,
    isActive: true,
    features: [
      "Custom features",
      "Dedicated infrastructure",
      "Personalized onboarding",
    ],
  },

  {
    id: 12,
    name: "Custom Ultimate",
    description: "Maximum customization for enterprise-grade requirements.",
    monthlyAmount: 14999,
    yearlyAmount: 149999,
    trialDays: 0,
    maxUsers: "Custom",
    maxProjects: "Custom",
    support: "Dedicated Technical Team",
    isPopular: false,
    isActive: true,
    features: [
      "Custom features",
      "Dedicated infrastructure",
      "Personalized onboarding",
    ],
  },
];
