import React from "react";
import Footer from "../components/ui/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AuthComponentLayOut = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
      <Footer />
    </html>
  );
};

export default AuthComponentLayOut;
