import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AuthComponentLayOut = ({ children }) => {
  return <>{children}</>;
};

export default AuthComponentLayOut;
